## Challenge: create a 5×5 matrix, compute its transpose, multiply it by itself, find the max value in each row — using only NumPy, no loops.

In [2]:
import numpy as np

In [4]:
array = np.random.random((5,5))
print(array)

[[0.12203669 0.81585342 0.05664702 0.07545286 0.23659194]
 [0.32317194 0.56667668 0.42225865 0.2193051  0.31376959]
 [0.80235034 0.83687838 0.96342998 0.62307539 0.95045983]
 [0.45741435 0.91905557 0.4363313  0.49135403 0.46480743]
 [0.42311946 0.3363612  0.98208798 0.94181014 0.60348048]]


In [5]:
print(array.T)

[[0.12203669 0.32317194 0.80235034 0.45741435 0.42311946]
 [0.81585342 0.56667668 0.83687838 0.91905557 0.3363612 ]
 [0.05664702 0.42225865 0.96342998 0.4363313  0.98208798]
 [0.07545286 0.2193051  0.62307539 0.49135403 0.94181014]
 [0.23659194 0.31376959 0.95045983 0.46480743 0.60348048]]


In [6]:
print(array*array)

[[0.01489295 0.6656168  0.00320889 0.00569313 0.05597574]
 [0.1044401  0.32112246 0.17830237 0.04809473 0.09845136]
 [0.64376607 0.70036542 0.92819732 0.38822294 0.90337388]
 [0.20922788 0.84466314 0.19038501 0.24142878 0.21604595]
 [0.17903008 0.11313886 0.96449681 0.88700634 0.36418869]]


In [9]:
print(array.max(axis = 1))

[0.81585342 0.56667668 0.96342998 0.91905557 0.98208798]
