In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
a.shape

(3, 5)

In [12]:
a.ndim

2

In [13]:
a.size

15

In [14]:
a.itemsize

8

In [15]:
a.dtype

dtype('int64')

In [19]:
type(a)

numpy.ndarray

In [24]:
a.ndim == len(a.shape)

True

In [27]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 8.48960859e-312,
       0.00000000e+000])

In [31]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.linspace(0,90,num=6)

array([ 0., 18., 36., 54., 72., 90.])

In [33]:
np.zeros(3 , dtype = np.int64)

array([0, 0, 0])

In [37]:
np.ones(8 , dtype = np.int64).reshape(2,2,2)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [39]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

(6,) means there is one axes and there are  6 elements along that axis numpy doesnot know whether it is a row or a column

In [43]:
a2 = a[np.newaxis, :]  #[new axis , all elements]
a2.shape

(1, 6)

In [44]:
a[:] #means give me all elements in existing axis


array([1, 2, 3, 4, 5, 6])

In [46]:
a3 = a[:,np.newaxis]
a3.shape
print(a3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [48]:
a4 = np.expand_dims(a , axis = 0)
a4.shape

(1, 6)

In [49]:
a5 = np.expand_dims(a , axis = 1)
a5.shape

(6, 1)

In [51]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<7])

[1 2 3 4 5 6]


In [54]:
b = np.nonzero(a<9)
print(b)

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2, 3]))


In [55]:
array = np.array([1,2,3,4,5,6,7,8,9])
arr1 = np.nonzero(a<5)
print(arr1)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


these are positions like 0 from the first braces and 0 from 2nd is [0,0] then [0,1] then [0,2]
No zeros means True(1) values 
-- First array is position of element in row and 2nd one is position of array in column


In [57]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
(np.int64(1), np.int64(0))
(np.int64(1), np.int64(1))
(np.int64(1), np.int64(2))
(np.int64(1), np.int64(3))


### zip is used to get the list of the coordinates of the elements who satisfied the condition

In [58]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


###

In [60]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
indices = [0,2,5]
print(indices)
print(numbers[indices])

[0, 2, 5]
[1 3 6]


In [62]:
where = np.where(numbers>5)
print(where)
print(numbers[where])

(array([5, 6, 7, 8]),)
[6 7 8 9]


In [65]:
condition = np.where(numbers > 5 , "True" , "False")
print(condition)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True']


In [69]:
a = np.array([[1,2] , [3,4]])
b = np.array([[5,6] , [7,8]])
c = np.vstack((a,b))
print(c)
d = np.hstack((a,b))
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [75]:
s = np.array([[1,2,3,4,5,6,7,8,9] , [11,12,13,14,15,16,17,18,19]])
splitted = np.hsplit(s,(2,5))
print(splitted)

[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4,  5],
       [13, 14, 15]]), array([[ 6,  7,  8,  9],
       [16, 17, 18, 19]])]


In [83]:
arrr = np.array([1,2,3,4,5,6,7,8])
spl = np.hsplit(arrr,(5,6))
print(spl)

[array([1, 2, 3, 4, 5]), array([6]), array([7, 8])]


### Broadcasting

In [88]:
array = np.array([[10,20,30,40] , [50,60,70,80]])
x = 10
print(array + x)
arrayy = np.array([100,200,300,400])
print(array + arrayy)

[[20 30 40 50]
 [60 70 80 90]]
[[110 220 330 440]
 [150 260 370 480]]


### Broadcasting in conditional operations

In [93]:
age = np.array([12,19,35,18,22,41,17,8,25,2,90])
status = np.array(["Adult" , "Minor"])
age_check = np.where(age>=18 , status[0] , status[1] )
print(age_check)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult' 'Minor' 'Minor' 'Adult'
 'Minor' 'Adult']


### Broadcasting for array manipulation

In [100]:
m = np.array([[1, 2], [3, 4]]).reshape(2,2)
v = np.array([10, 20]).reshape(1,2)
res = m * v
print(res)

[[10 40]
 [30 80]]


m*v and v*m is used according to the demensions to meet the compatibility rule


In [105]:
print(age.min())
print(age.max())
print(array.max(axis = 0))
print(array.max(axis = 1))
print(array.max())

2
90
[50 60 70 80]
[40 80]
80


In [109]:
a = np.array([1,1,3,4,6,4,2,4,6,7,4,2,4,6,8,9,12,5,3,4,5,6,44,5,6,7,6,5])
unique_a = np.unique(a)
print(unique_a)

[ 1  2  3  4  5  6  7  8  9 12 44]


In [112]:
abcd,ind = np.unique(a , return_index = True)
print(ind)

[ 0  6  2  3 17  4  9 14 15 16 22]


### Flip/Reverse 

In [113]:
print(np.flip(a))

[ 5  6  7  6  5 44  6  5  4  3  5 12  9  8  6  4  2  4  7  6  4  2  4  6
  4  3  1  1]


In [114]:
print(np.flip(m))

[[4 3]
 [2 1]]


In [116]:
print(np.flip(m[0]))

[2 1]


In [117]:
print(np.flip(m[:,1]))

[4 2]


In [119]:
a = np.array([[1,2,] , [3,4]])
b = np.array([[5,6] , [7,8]])
c = np.dot(a,b)
print(c)
d = a@b
print(d)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
